// Approximate centroid coordinates (J2000, RA in hours, Dec in degrees)
// for well-known constellations + the Moon/Sun/visible planets are handled separately.
// These centroids are good enough for "is this constellation roughly overhead" purposes.
const CONSTELLATIONS = [
  { name: "Ursa Major",      ra: 11.0, dec: 55.0,  wiki: "Ursa Major" },
  { name: "Ursa Minor",      ra: 15.0, dec: 75.0,  wiki: "Ursa Minor" },
  { name: "Cassiopeia",      ra: 1.0,  dec: 60.0,  wiki: "Cassiopeia (constellation)" },
  { name: "Cepheus",         ra: 22.0, dec: 70.0,  wiki: "Cepheus (constellation)" },
  { name: "Draco",           ra: 17.0, dec: 65.0,  wiki: "Draco (constellation)" },
  { name: "Orion",           ra: 5.5,  dec: 5.0,   wiki: "Orion (constellation)" },
  { name: "Canis Major",     ra: 6.8,  dec: -22.0, wiki: "Canis Major" },
  { name: "Canis Minor",     ra: 7.6,  dec: 6.0,   wiki: "Canis Minor" },
  { name: "Taurus",          ra: 4.5,  dec: 16.0,  wiki: "Taurus (constellation)" },
  { name: "Gemini",          ra: 7.0,  dec: 22.0,  wiki: "Gemini (constellation)" },
  { name: "Leo",             ra: 10.7, dec: 13.0,  wiki: "Leo (constellation)" },
  { name: "Virgo",           ra: 13.4, dec: -4.0,  wiki: "Virgo (constellation)" },
  { name: "Libra",           ra: 15.2, dec: -15.0, wiki: "Libra (constellation)" },
  { name: "Scorpius",        ra: 16.9, dec: -30.0, wiki: "Scorpius" },
  { name: "Sagittarius",     ra: 19.0, dec: -25.0, wiki: "Sagittarius (constellation)" },
  { name: "Capricornus",     ra: 21.0, dec: -18.0, wiki: "Capricornus" },
  { name: "Aquarius",        ra: 22.3, dec: -10.0, wiki: "Aquarius (constellation)" },
  { name: "Pisces",          ra: 0.9,  dec: 10.0,  wiki: "Pisces (constellation)" },
  { name: "Aries",           ra: 2.6,  dec: 20.0,  wiki: "Aries (constellation)" },
  { name: "Cancer",          ra: 8.6,  dec: 20.0,  wiki: "Cancer (constellation)" },
  { name: "Lyra",            ra: 18.8, dec: 36.0,  wiki: "Lyra" },
  { name: "Cygnus",          ra: 20.6, dec: 42.0,  wiki: "Cygnus (constellation)" },
  { name: "Aquila",          ra: 19.7, dec: 3.0,   wiki: "Aquila (constellation)" },
  { name: "Pegasus",         ra: 22.7, dec: 19.0,  wiki: "Pegasus (constellation)" },
  { name: "Andromeda",       ra: 0.8,  dec: 38.0,  wiki: "Andromeda (constellation)" },
  { name: "Perseus",         ra: 3.2,  dec: 45.0,  wiki: "Perseus (constellation)" },
  { name: "Auriga",          ra: 6.0,  dec: 42.0,  wiki: "Auriga (constellation)" },
  { name: "Boötes",          ra: 14.7, dec: 31.0,  wiki: "Boötes" },
  { name: "Corona Borealis", ra: 15.8, dec: 32.0,  wiki: "Corona Borealis" },
  { name: "Hercules",        ra: 17.4, dec: 27.0,  wiki: "Hercules (constellation)" },
  { name: "Ophiuchus",       ra: 17.0, dec: -8.0,  wiki: "Ophiuchus" },
  { name: "Crux",            ra: 12.4, dec: -60.0, wiki: "Crux" },
  { name: "Centaurus",       ra: 13.0, dec: -47.0, wiki: "Centaurus" },
  { name: "Carina",          ra: 8.7,  dec: -63.0, wiki: "Carina (constellation)" },
  { name: "Phoenix",         ra: 0.9,  dec: -48.0, wiki: "Phoenix (constellation)" },
  { name: "Eridanus",        ra: 3.3,  dec: -28.0, wiki: "Eridanus (constellation)" },
  { name: "Lepus",           ra: 5.6,  dec: -19.0, wiki: "Lepus (constellation)" },
  { name: "Columba",         ra: 5.9,  dec: -35.0, wiki: "Columba (constellation)" },
  { name: "Corvus",          ra: 12.4, dec: -18.0, wiki: "Corvus (constellation)" },
  { name: "Hydra",           ra: 11.6, dec: -14.0, wiki: "Hydra (constellation)" },
  { name: "Sculptor",        ra: 0.4,  dec: -32.0, wiki: "Sculptor (constellation)" },
  { name: "Pavo",            ra: 19.6, dec: -65.0, wiki: "Pavo (constellation)" },
  { name: "Tucana",          ra: 23.8, dec: -65.0, wiki: "Tucana" },
  { name: "Triangulum",      ra: 2.2,  dec: 32.0,  wiki: "Triangulum (constellation)" },
];
